-- Create DB + schemas
CREATE DATABASE IF NOT EXISTS COVID_DEMO;

CREATE SCHEMA IF NOT EXISTS COVID_DEMO.RAW;
CREATE SCHEMA IF NOT EXISTS COVID_DEMO.CURATED;
CREATE SCHEMA IF NOT EXISTS COVID_DEMO.MART;
CREATE SCHEMA IF NOT EXISTS COVID_DEMO.OPS;
