USE DATABASE COVID_DEMO;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT FF_CSV_DEFAULT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL', 'null')
    TRIM_SPACE = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;
