USE DATABASE COVID_DEMO;
USE SCHEMA RAW;

-- Internal stage for COVID files
CREATE STAGE IF NOT EXISTS STG_COVID_FILES
    FILE_FORMAT = FF_CSV_DEFAULT;

-- Internal stage for City files
CREATE STAGE IF NOT EXISTS STG_CITY_FILES
    FILE_FORMAT = FF_CSV_DEFAULT;

-- Internal stage for Country files
CREATE STAGE IF NOT EXISTS STG_COUNTRY_FILES
    FILE_FORMAT = FF_CSV_DEFAULT;
