USE DATABASE COVID_DEMO;
USE SCHEMA OPS;

CREATE OR REPLACE TASK RAW.TASK_LOAD_COVID_DAILY
    WAREHOUSE = WH_COVID_INGEST
    SCHEDULE = 'USING CRON 0 0 * * * UTC'
AS
COPY INTO RAW.COVID_DAILY_RAW
FROM (
    SELECT
        $1  AS fips,
        $2  AS admin2,
        $3  AS province_state,
        $4  AS country_region,
        $5  AS last_update,
        $6  AS lat,
        $7  AS long_,
        $8  AS confirmed,
        $9  AS deaths,
        $10 AS recovered,
        $11 AS active,
        METADATA$FILENAME AS source_file,
        METADATA$FILE_ROW_NUMBER AS source_row,
        CURRENT_TIMESTAMP() AS ingested_at
    FROM @RAW.STG_COVID_FILES/
)
FILE_FORMAT = (FORMAT_NAME = RAW.FF_CSV_DEFAULT)
ON_ERROR = 'CONTINUE';


CREATE OR REPLACE TASK OPS.TASK_BUILD_SILVER
    WAREHOUSE = WH_COVID_INGEST
    AFTER RAW.TASK_LOAD_COVID_DAILY
AS
    CALL OPS.SP_BUILD_SILVER();

CREATE OR REPLACE TASK OPS.TASK_RUN_DQ
    WAREHOUSE = WH_COVID_INGEST
    AFTER OPS.TASK_BUILD_SILVER
AS
    CALL OPS.SP_RUN_DQ();

CREATE OR REPLACE TASK OPS.TASK_BUILD_GOLD
    WAREHOUSE = WH_COVID_INGEST
    AFTER OPS.TASK_RUN_DQ
AS
    CALL OPS.SP_BUILD_GOLD();

-- Running the task
-- ALTER TASK OPS.TASK_LOAD_COVID_DAILY RESUME;
-- ALTER TASK OPS.TASK_BUILD_SILVER     RESUME;
-- ALTER TASK OPS.TASK_BUILD_GOLD       RESUME;
-- ALTER TASK OPS.TASK_RUN_DQ           RESUME;