USE DATABASE COVID_DEMO;
USE SCHEMA OPS;

CREATE OR REPLACE TASK OPS.TASK_BUILD_SILVER
    WAREHOUSE = WH_COVID_INGEST
    SCHEDULE = 'USING CRON 0 0 * * * UTC'
AS
    CALL OPS.SP_BUILD_SILVER();

CREATE OR REPLACE TASK OPS.TASK_RUN_DQ
    WAREHOUSE = WH_COVID_INGEST
    AFTER OPS.TASK_BUILD_SILVER
AS
    CALL OPS.SP_RUN_DQ();

CREATE OR REPLACE TASK OPS.TASK_BUILD_GOLD
    WAREHOUSE = WH_COVID_INGEST
    AFTER OPS.TASK_RUN_DQ
AS
    CALL OPS.SP_BUILD_GOLD();

-- Running the task
-- ALTER TASK OPS.TASK_BUILD_SILVER RESUME;
-- ALTER TASK OPS.TASK_BUILD_GOLD   RESUME;
-- ALTER TASK OPS.TASK_RUN_DQ       RESUME;