USE DATABASE COVID_DEMO;
USE SCHEMA OPS;


CREATE OR REPLACE TASK OPS.TASK_BUILD_SILVER
	WAREHOUSE = WH_COVID
	SCHEDULE = '15 MINUTE'
AS
  	CALL OPS.SP_BUILD_SILVER();

CREATE OR REPLACE TASK OPS.TASK_BUILD_GOLD
	WAREHOUSE = WH_COVID
	AFTER OPS.TASK_BUILD_SILVER
AS
  	CALL OPS.SP_BUILD_GOLD();

CREATE OR REPLACE TASK OPS.TASK_RUN_DQ
	WAREHOUSE = WH_COVID
	AFTER OPS.TASK_BUILD_GOLD
AS
  	CALL OPS.SP_RUN_DQ();

-- Enable
-- ALTER TASK OPS.TASK_BUILD_SILVER RESUME;
-- ALTER TASK OPS.TASK_BUILD_GOLD RESUME;
-- ALTER TASK OPS.TASK_RUN_DQ RESUME;
